Plotly is a library that allows you to create interactive plots that you can use in dashboards or websites (you can save them as html files or static images).

## Installation

In order for this all to work, you'll need to install plotly and cufflinks to call plots directly off of a pandas dataframe. These libraries are not currently available through **conda** but are available through **pip**. Install the libraries at your command line/terminal using:

    pip install plotly
    pip install cufflinks

** NOTE: Make sure you only have one installation of Python on your computer when you do this, otherwise the installation may not work. **

## Imports and Set-up

In [6]:
import pandas as pd
import numpy as np
%matplotlib inline

In [ ]:
!pip install -U plotly cufflinks

Requirement already satisfied: plotly in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (4.14.3)
Collecting plotly
  Using cached plotly-6.3.1-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: cufflinks in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (0.17.3)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from plotly) (2.9.0)
Requirement already satisfied: packaging in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from plotly) (25.0)
Requirement already satisfied: numpy>=1.9.2 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from cufflinks) (2.2.5)
Requirement already satisfied: pandas>=0.19.2 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from cufflinks) (2.2.3)
Requirement already satisfied: six>=1.9.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from cufflinks) (1.17.0)
Requirement already satisfied: colorlover>=0.2.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from cufflinks) (0.3.0)
Requirement already satisfied: setuptools>=34.4.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from cufflinks) (75.3.0)
Requirement already satisfied: ipython>=5.3.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from cufflinks) (9.2.0)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from cufflinks) (8.1.1)
Requirement already satisfied: colorama in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from ipython>=5.3.0->cufflinks) (0.4.6)
Requirement already satisfied: decorator in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from ipython>=5.3.0->cufflinks) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from ipython>=5.3.0->cufflinks) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from ipython>=5.3.0->cufflinks) (2.19.1)
Requirement already satisfied: stack_data in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from ipython>=5.3.0->cufflinks) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.14.3)
Requirement already satisfied: comm>=0.1.3 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (0.2.2)
Requirement already satisfied: widgetsnbextension~=4.0.9 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from ipywidgets>=7.0.0->cufflinks) (4.0.9)
Requirement already satisfied: jupyterlab-widgets~=3.0.9 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from ipywidgets>=7.0.0->cufflinks) (3.0.9)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.19.2->cufflinks) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.19.2->cufflinks) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.19.2->cufflinks) (2025.2)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->cufflinks) (0.8.4)
Requirement already satisfied: wcwidth in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->cufflinks) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from stack_data->ipython>=5.3.0->cufflinks) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from stack_data->ipython>=5.3.0->cufflinks) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from stack_data->ipython>=5.3.0->cufflinks) (0.2.3)
Using cached plotly-6.3.1-py3-none-any.whl (9.8 MB)
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 4.14.3
    Uninstalling plotly-4.14.3:
      Successfully uninstalled plotly-4.14.3
Successfully installed plotly-6.3.1

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__)

6.3.1

In [3]:
import cufflinks as cf

In [4]:
# For Notebooks
init_notebook_mode(connected=True)

In [9]:
# For offline use
cf.go_offline()

### Fake Data

In [8]:
df = pd.DataFrame(np.random.randn(100,4),columns='A B C D'.split())

In [9]:
df.head()

          A         B         C         D
0  0.288869  0.953198  0.277210 -1.343862
1  0.747431  0.702096 -1.341331  0.061045
2 -0.021048  0.373105  1.418422  0.529828
3 -1.078978  1.578691 -0.908615 -0.931327
4  1.068293 -1.531972 -0.756936  1.073338

In [10]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})

In [11]:
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50

## Using Cufflinks and iplot()

* scatter
* bar
* box
* spread
* ratio
* heatmap
* surface
* histogram
* bubble

## Scatter

In [ ]:
!pip uninstall plotly
!pip install plotly --upgrade

In [12]:
import plotly.io as pio
import plotly.express as px

# Reset to default template
pio.templates.default = "plotly"

# Now create your plot
fig = px.scatter(df, x='A', y='B', title='Scatter Plot')
fig.show()

## Bar Plots

In [28]:
df2.iplot(kind='bar',x='Category',y='Values')

In [33]:
df.count().iplot(kind='bar')

## Boxplots

In [34]:
df.iplot(kind='box')

## 3d Surface

In [47]:
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})
df3.iplot(kind='surface',colorscale='rdylbu')

## Spread

In [50]:
df[['A','B']].iplot(kind='spread')

## histogram

In [56]:
df['A'].iplot(kind='hist',bins=25)

In [60]:
df.iplot(kind='bubble',x='A',y='B',size='C')

## scatter_matrix()

Similar to sns.pairplot()

In [13]:
df.scatter_matrix()

# Great Job!